[project]
name = "python-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "google-genai>=1.7.0",
    "httpx>=0.28.1",
    "mcp>=1.5.0",
    "python-dotenv>=1.0.1",
]

[tool.setuptools]
py-modules = ["main", "mcp_chat_app", "mcp_flask_backend"]
